server:
  port: ${SERVER_PORT:8444}
  servlet:
    context-path: /admin

spring:
  application:
    name: w-service-like
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${ATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/${DATASOURCE:wahaha}?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:qwas1234}

# mybatis #  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
mybatis-plus:
  mapper-locations: classpath*:com.me.only.repository.mapper/*Mapper.xml

  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.me.only.repository.entity

logging:
  level:
    com.me.only.repository.mapper: DEBUG
