server:
  port: ${SERVER_PORT:8444}
  servlet:
    context-path: /admin

spring:
  application:
    name: admin-service

  #数据库链接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${ATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/${DATASOURCE:only-admin}?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:szh1234mysql}
